markdown: rdiscount
safe: true
lsi: false
pygments: true
permalink: /posts/:title
title : FuriKuri's Blog
production_url : https://furikuri.github.io
description: "My Blog"
disqus_shortname: furikurisblog
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
author :
  name : Theo Pack
  github : FuriKuri
  twitter : furikuri
  email: tf.pack@gmail.com
